/** @type {import('tailwindcss').Config} */
import forms from '@tailwindcss/forms';

export default {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx,vue,svelte,md,mdx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-container': '#b9eeab',
        'on-error-container': '#93000a',
        'on-secondary-container': '#3f6d38',
        'outline-variant': '#d0c5af',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-tertiary': '#ffffff',
        'clotted-cream': '#FCF9F2',
        'silk-white': '#FFFFFF',
        'surface-bright': '#F7F3EA',
        tertiary: '#415ba4',
        outline: '#7f7663',
        surface: '#F7F3EA',
        'tertiary-fixed-dim': '#b4c5ff',
        secondary: '#3b6934',
        'on-primary': '#ffffff',
        'antique-gold': '#D4AF37',
        'surface-container-highest': '#DFD7C4',
        'lava-stone': '#333333',
        'tertiary-fixed': '#dbe1ff',
        'secondary-fixed-dim': '#a1d494',
        'primary-fixed': '#ffe088',
        'surface-container': '#ECE6D8',
        'on-surface': '#1d1d03',
        'on-surface-variant': '#4d4635',
        'surface-dim': '#D7CEB9',
        'surface-variant': '#DFD7C4',
        'tertiary-container': '#97b0ff',
        'primary-fixed-dim': '#e9c349',
        'on-tertiary-fixed': '#00174b',
        'on-error': '#ffffff',
        primary: '#735c00',
        'secondary-fixed': '#bcf0ae',
        'on-tertiary-fixed-variant': '#27438a',
        'inverse-primary': '#e9c349',
        'primary-container': '#d4af37',
        'vesuvius-green': '#2D5A27',
        'inverse-on-surface': '#F2EDE1',
        terracotta: '#E2725B',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#23501e',
        'on-primary-container': '#554300',
        'on-primary-fixed-variant': '#574500',
        'surface-tint': '#735c00',
        'on-background': '#1d1d03',
        'on-secondary-fixed': '#002201',
        'surface-container-high': '#E5DECD',
        'inverse-surface': '#323214',
        background: '#F7F3EA',
        'on-primary-fixed': '#241a00',
        'on-secondary': '#ffffff',
        'on-tertiary-container': '#254188',
        'surface-container-low': '#F2EDE1',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        unit: '8px',
        'container-max': '1280px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
        gutter: '24px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'label-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['"Libre Caslon Text"', 'serif'],
        'headline-md': ['"Libre Caslon Text"', 'serif'],
        'headline-display': ['"Libre Caslon Text"', 'serif'],
        'headline-lg': ['"Libre Caslon Text"', 'serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '400' }],
        'headline-display': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '400' }],
      },
    },
  },
  plugins: [forms],
};
